### ISSUE TITLE
ERROR : scons not found 

### ISSUE THREAD

**Issue by vivekruhela** [egaffo/mirandmore2#1]
I am trying to run mir&more2 pipeline on our data and everytime while running `install_mnm2` file, I always get an error at line no. 29 which says that `scons: command not found`. I have checked that module is already install but it is not working. Even I manually set the symbolic link that was done at line no.  23 still the error persists. I have attached the screenshot of the error. Please suggest. Thanks.

[EDIT-1] : Adding little bit more about how I debug it. I run the command `python scon.py` from `$TOOL_DIR/scons/` directory to check if the module is working and yes it is working fine but the symbolic link at line_no 23 of `install_mnm2` script may not be properly (or effectively) working because by calling `scons` from command prompt it is calling only `$TOOL_DIR/scons/scons.py` without telling bash how to run it (i.e. without python) (please let me know If I missed anything)
![Screenshot (146)](https://user-images.githubusercontent.com/13174913/83416687-a9af7f80-a43e-11ea-8a34-15d6ee9dc0a6.png)

**Comment by egaffo** [comment]
do you have the permission to run the scons.py ? that file has the #! /usr/bin/env python head line (shebang line) and does not need the python interepreter to be explicitely invoked by the user. However, it need to be executable (chmod +x scons.py is the command to set the exec  permission).
At line 29 the script then assume the scons executable (or at least the symlink to scons) is visible in your environment, which should be set by line 5 of the script that updates the PATH variable by including the MiR&moRe2 bin/ dir.
Maybe your system has problems with updating the environment PATH? Which OS are you running?

**Comment by vivekruhela** [comment]
Sorry for late response.  I am still not able to install this pipeline even after following `install_mnm2` script line by line. script is working fine till line 28 but line 29 is not working. Environment variable are updated as I have checked manually but last line still showing an error. What else I am missing here?

EDIT-1: Issue is solved. Probably this is due to remotely accessing the server and issue with updating the env variable. Now all the tools are properly installed. But when I test this on my data then now I am getting this error:

`scons: Reading SConscript files ...`

`scons: warning: Calling missing SConscript without error is deprecated.
Transition by adding must_exist=0 to SConscript calls.
Missing SConscript 'mirandmore_dbs/bwt_genome_index/mirandmore_bowtie_index'
File "/mnt/disk2/Mirpipe/mirandmore2/src/sconstructs/main.py", line 145, in <module>
TypeError: 'NoneType' object is not subscriptable:
  File "/mnt/disk2/Mirpipe/mirandmore2/src/sconstructs/main.py", line 147:
    env.Replace(BOWTIE_GENOME_INDEX = genome_bowtie_index[0].abspath[:-7])`

I don't get the meaning of this error (because now every required tool is present and intalled). Please suggest. Thanks.

**Comment by egaffo** [comment]
That might be a bug in miR&moRe2 that I'll check. It is generated because the file name of the SConscript to build the Bowtie index was not updated in the code. 
Meanwhile, you can manually build the genome index (or download a precomputed one, if available) and set the BOWTIE_GENOME_INDEX parameter accordingly, so the bugged part of the pipeline will be skipped. Moreover, I suggest this last approach to run the analyses, since building a genome index i a very time consuming step.

**Comment by vivekruhela** [comment]
Yes. I have generated the genome index manually and set the BOWTIE_GENOME_INDEX parameter. After that it worked fine. But again I have faced an issue (small code bug) which I have to debugged fixed manually. I think I should inform you to further cross-check that.

![Screenshot (149)](https://user-images.githubusercontent.com/13174913/83983907-ad1b9d00-a94f-11ea-88ad-e06c96ca7c07.png)


I have an issue on `pre_summary_to_mature_table.py` file at line no. 51 [screenshot attached] which was related to type error. As it is clear that variable of type only sting can be joined to another string variable (not variable of type int). So I have to change line 51  from `" 
".join(known_mature_tab[pre]['matures'][name].values())` to `" ".join(str(known_mature_tab[pre]['matures'][name].values()))` and then it worked fine. I have got all the result as desired. Thanks.

EDIT-1: One more point I would like to raise here is that in `result/read_quality_stats/depth.csv` file, both input and output reads are 100000 (0.1 million) but in `filter_report.txt`, it shows only 97120 reads processed and 0 reads discarded. Why remaining 2810 reads are not processed if 0 reads are discarded. It sound confusing to me. Please elaborate. Thanks.

**Comment by egaffo** [comment]
Thanks for the bugfix suggestion, I will fix in next release.
The depth.csv file collects output form the cutadapt log (you find it in each sample "trimmed_reads" subdirectory. In particular "Total reads processed" and "Reads written (passing filters)" lines. The "processed reads" in filter_report.txt (which collect statistics from the filter_trimmed.py script) should indeed be equal to "output" in depth.csv.  
As I cannot replicate the behaviour you described, could you provide me with the data causing this error along with the parameters you used?
Please, open a new issue for that, since this is another topic with respect to this issue title.
